# Generated by Django 3.2.7 on 2021-09-26 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios',
            name='destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cambio_destino', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cambios',
            name='origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cambio_origen', to=settings.AUTH_USER_MODEL),
        ),
    ]
