# Generated by Django 3.2.7 on 2021-10-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0002_auto_20210926_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios',
            name='tipo',
            field=models.CharField(choices=[('Dorado', 'dorado'), ('Azul', 'azul')], max_length=6),
        ),
    ]
