# Generated by Django 3.2.7 on 2021-10-05 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estado', '0003_alter_cambios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios',
            name='destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destino_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cambios',
            name='origen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origen_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
