# Generated by Django 3.2.7 on 2021-10-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0004_auto_20211005_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios',
            name='tipo',
            field=models.CharField(choices=[('Naranja', 'naranja'), ('Azul', 'azul')], max_length=10),
        ),
    ]
