# Generated by Django 3.2.7 on 2021-11-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0006_cambios_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios',
            name='mensaje',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mensaje'),
        ),
    ]
